# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/training_game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/training_game.proto',
  package='hexit',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17src/training_game.proto\x12\x05hexit\"\x9e\x02\n\x0cTrainingGame\x12\x37\n\rmoveSnapshots\x18\x01 \x03(\x0b\x32 .hexit.TrainingGame.MoveSnapshot\x1a\xac\x01\n\x0cMoveSnapshot\x12!\n\x15normalizedVisitCounts\x18\x01 \x03(\x02\x42\x02\x10\x01\x12*\n\x06winner\x18\x02 \x01(\x0e\x32\x1a.hexit.TrainingGame.Player\x12#\n\x17squaresOccupiedByMyself\x18\x03 \x03(\x02\x42\x02\x10\x01\x12(\n\x1csquaresOccupiedByOtherPlayer\x18\x04 \x03(\x02\x42\x02\x10\x01\"&\n\x06Player\x12\n\n\x06MYSELF\x10\x00\x12\x10\n\x0cOTHER_PLAYER\x10\x01\x62\x06proto3')
)



_TRAININGGAME_PLAYER = _descriptor.EnumDescriptor(
  name='Player',
  full_name='hexit.TrainingGame.Player',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MYSELF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER_PLAYER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=283,
  serialized_end=321,
)
_sym_db.RegisterEnumDescriptor(_TRAININGGAME_PLAYER)


_TRAININGGAME_MOVESNAPSHOT = _descriptor.Descriptor(
  name='MoveSnapshot',
  full_name='hexit.TrainingGame.MoveSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='normalizedVisitCounts', full_name='hexit.TrainingGame.MoveSnapshot.normalizedVisitCounts', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winner', full_name='hexit.TrainingGame.MoveSnapshot.winner', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squaresOccupiedByMyself', full_name='hexit.TrainingGame.MoveSnapshot.squaresOccupiedByMyself', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squaresOccupiedByOtherPlayer', full_name='hexit.TrainingGame.MoveSnapshot.squaresOccupiedByOtherPlayer', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=281,
)

_TRAININGGAME = _descriptor.Descriptor(
  name='TrainingGame',
  full_name='hexit.TrainingGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='moveSnapshots', full_name='hexit.TrainingGame.moveSnapshots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRAININGGAME_MOVESNAPSHOT, ],
  enum_types=[
    _TRAININGGAME_PLAYER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=321,
)

_TRAININGGAME_MOVESNAPSHOT.fields_by_name['winner'].enum_type = _TRAININGGAME_PLAYER
_TRAININGGAME_MOVESNAPSHOT.containing_type = _TRAININGGAME
_TRAININGGAME.fields_by_name['moveSnapshots'].message_type = _TRAININGGAME_MOVESNAPSHOT
_TRAININGGAME_PLAYER.containing_type = _TRAININGGAME
DESCRIPTOR.message_types_by_name['TrainingGame'] = _TRAININGGAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainingGame = _reflection.GeneratedProtocolMessageType('TrainingGame', (_message.Message,), dict(

  MoveSnapshot = _reflection.GeneratedProtocolMessageType('MoveSnapshot', (_message.Message,), dict(
    DESCRIPTOR = _TRAININGGAME_MOVESNAPSHOT,
    __module__ = 'src.training_game_pb2'
    # @@protoc_insertion_point(class_scope:hexit.TrainingGame.MoveSnapshot)
    ))
  ,
  DESCRIPTOR = _TRAININGGAME,
  __module__ = 'src.training_game_pb2'
  # @@protoc_insertion_point(class_scope:hexit.TrainingGame)
  ))
_sym_db.RegisterMessage(TrainingGame)
_sym_db.RegisterMessage(TrainingGame.MoveSnapshot)


_TRAININGGAME_MOVESNAPSHOT.fields_by_name['normalizedVisitCounts']._options = None
_TRAININGGAME_MOVESNAPSHOT.fields_by_name['squaresOccupiedByMyself']._options = None
_TRAININGGAME_MOVESNAPSHOT.fields_by_name['squaresOccupiedByOtherPlayer']._options = None
# @@protoc_insertion_point(module_scope)
