// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/training_game.proto

package hexit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TrainingGame_Player int32

const (
	TrainingGame_MYSELF       TrainingGame_Player = 0
	TrainingGame_OTHER_PLAYER TrainingGame_Player = 1
)

var TrainingGame_Player_name = map[int32]string{
	0: "MYSELF",
	1: "OTHER_PLAYER",
}
var TrainingGame_Player_value = map[string]int32{
	"MYSELF":       0,
	"OTHER_PLAYER": 1,
}

func (x TrainingGame_Player) String() string {
	return proto.EnumName(TrainingGame_Player_name, int32(x))
}
func (TrainingGame_Player) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_training_game_2456b92fc52b1182, []int{0, 0}
}

type TrainingGame struct {
	MoveSnapshots        []*TrainingGame_MoveSnapshot `protobuf:"bytes,1,rep,name=moveSnapshots,proto3" json:"moveSnapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TrainingGame) Reset()         { *m = TrainingGame{} }
func (m *TrainingGame) String() string { return proto.CompactTextString(m) }
func (*TrainingGame) ProtoMessage()    {}
func (*TrainingGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_training_game_2456b92fc52b1182, []int{0}
}
func (m *TrainingGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainingGame.Unmarshal(m, b)
}
func (m *TrainingGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainingGame.Marshal(b, m, deterministic)
}
func (dst *TrainingGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingGame.Merge(dst, src)
}
func (m *TrainingGame) XXX_Size() int {
	return xxx_messageInfo_TrainingGame.Size(m)
}
func (m *TrainingGame) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingGame.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingGame proto.InternalMessageInfo

func (m *TrainingGame) GetMoveSnapshots() []*TrainingGame_MoveSnapshot {
	if m != nil {
		return m.MoveSnapshots
	}
	return nil
}

type TrainingGame_MoveSnapshot struct {
	NormalizedVisitCounts []float32           `protobuf:"fixed32,1,rep,packed,name=normalizedVisitCounts,proto3" json:"normalizedVisitCounts,omitempty"`
	Winner                TrainingGame_Player `protobuf:"varint,2,opt,name=winner,proto3,enum=hexit.TrainingGame_Player" json:"winner,omitempty"`
	// 25 floats, one per board square.
	// 1.0 if occupied, 0.0 if not
	SquaresOccupiedByMyself      []float32 `protobuf:"fixed32,3,rep,packed,name=squaresOccupiedByMyself,proto3" json:"squaresOccupiedByMyself,omitempty"`
	SquaresOccupiedByOtherPlayer []float32 `protobuf:"fixed32,4,rep,packed,name=squaresOccupiedByOtherPlayer,proto3" json:"squaresOccupiedByOtherPlayer,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}  `json:"-"`
	XXX_unrecognized             []byte    `json:"-"`
	XXX_sizecache                int32     `json:"-"`
}

func (m *TrainingGame_MoveSnapshot) Reset()         { *m = TrainingGame_MoveSnapshot{} }
func (m *TrainingGame_MoveSnapshot) String() string { return proto.CompactTextString(m) }
func (*TrainingGame_MoveSnapshot) ProtoMessage()    {}
func (*TrainingGame_MoveSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_training_game_2456b92fc52b1182, []int{0, 0}
}
func (m *TrainingGame_MoveSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainingGame_MoveSnapshot.Unmarshal(m, b)
}
func (m *TrainingGame_MoveSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainingGame_MoveSnapshot.Marshal(b, m, deterministic)
}
func (dst *TrainingGame_MoveSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingGame_MoveSnapshot.Merge(dst, src)
}
func (m *TrainingGame_MoveSnapshot) XXX_Size() int {
	return xxx_messageInfo_TrainingGame_MoveSnapshot.Size(m)
}
func (m *TrainingGame_MoveSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingGame_MoveSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingGame_MoveSnapshot proto.InternalMessageInfo

func (m *TrainingGame_MoveSnapshot) GetNormalizedVisitCounts() []float32 {
	if m != nil {
		return m.NormalizedVisitCounts
	}
	return nil
}

func (m *TrainingGame_MoveSnapshot) GetWinner() TrainingGame_Player {
	if m != nil {
		return m.Winner
	}
	return TrainingGame_MYSELF
}

func (m *TrainingGame_MoveSnapshot) GetSquaresOccupiedByMyself() []float32 {
	if m != nil {
		return m.SquaresOccupiedByMyself
	}
	return nil
}

func (m *TrainingGame_MoveSnapshot) GetSquaresOccupiedByOtherPlayer() []float32 {
	if m != nil {
		return m.SquaresOccupiedByOtherPlayer
	}
	return nil
}

func init() {
	proto.RegisterType((*TrainingGame)(nil), "hexit.TrainingGame")
	proto.RegisterType((*TrainingGame_MoveSnapshot)(nil), "hexit.TrainingGame.MoveSnapshot")
	proto.RegisterEnum("hexit.TrainingGame_Player", TrainingGame_Player_name, TrainingGame_Player_value)
}

func init() {
	proto.RegisterFile("src/training_game.proto", fileDescriptor_training_game_2456b92fc52b1182)
}

var fileDescriptor_training_game_2456b92fc52b1182 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd1, 0xb1, 0x4b, 0xc3, 0x40,
	0x14, 0x06, 0x70, 0x93, 0x6a, 0x86, 0x67, 0x94, 0x70, 0x20, 0x0d, 0xc5, 0x21, 0x74, 0x90, 0x4e,
	0x11, 0xe2, 0xe2, 0xe0, 0x62, 0x25, 0xd1, 0xa1, 0x21, 0x25, 0x2d, 0x42, 0xa7, 0x72, 0xa6, 0xcf,
	0xe6, 0x20, 0xb9, 0x8b, 0x77, 0x17, 0x35, 0x8e, 0xfa, 0x8f, 0x0b, 0x6d, 0x28, 0x11, 0xab, 0xdb,
	0xc1, 0xf7, 0xbb, 0xf7, 0x3d, 0x78, 0xd0, 0x57, 0x32, 0xbb, 0xd4, 0x92, 0x32, 0xce, 0xf8, 0x7a,
	0xb9, 0xa6, 0x25, 0xfa, 0x95, 0x14, 0x5a, 0x90, 0xa3, 0x1c, 0xdf, 0x99, 0x1e, 0x7e, 0xf5, 0xc0,
	0x9e, 0xb7, 0xf1, 0x3d, 0x2d, 0x91, 0x44, 0x70, 0x52, 0x8a, 0x57, 0x9c, 0x71, 0x5a, 0xa9, 0x5c,
	0x68, 0xe5, 0x1a, 0x5e, 0x6f, 0x74, 0x1c, 0x78, 0xfe, 0xc6, 0xfb, 0x5d, 0xeb, 0xc7, 0x1d, 0x98,
	0xfe, 0xfc, 0x36, 0xf8, 0x34, 0xc1, 0xee, 0xe6, 0xe4, 0x1a, 0xce, 0xb8, 0x90, 0x25, 0x2d, 0xd8,
	0x07, 0xae, 0x1e, 0x99, 0x62, 0xfa, 0x4e, 0xd4, 0xbc, 0x2d, 0x30, 0xc7, 0xa6, 0x63, 0xa4, 0xfb,
	0x01, 0x09, 0xc0, 0x7a, 0x63, 0x9c, 0xa3, 0x74, 0x4d, 0xcf, 0x18, 0x9d, 0x06, 0x83, 0x7d, 0xbb,
	0x4c, 0x0b, 0xda, 0xa0, 0x4c, 0x5b, 0x49, 0x6e, 0xa0, 0xaf, 0x5e, 0x6a, 0x2a, 0x51, 0x25, 0x59,
	0x56, 0x57, 0x0c, 0x57, 0xe3, 0x26, 0x6e, 0x14, 0x16, 0xcf, 0x6e, 0x6f, 0xd7, 0xf7, 0x17, 0x21,
	0x11, 0x9c, 0xff, 0x8a, 0x12, 0x9d, 0xa3, 0xdc, 0xb6, 0xb8, 0x87, 0xbb, 0x11, 0xff, 0xba, 0xe1,
	0x05, 0x58, 0xdb, 0x17, 0x01, 0xb0, 0xe2, 0xc5, 0x2c, 0x9c, 0x44, 0xce, 0x01, 0x71, 0xc0, 0x4e,
	0xe6, 0x0f, 0x61, 0xba, 0x9c, 0x4e, 0x6e, 0x17, 0x61, 0xea, 0x18, 0x4f, 0xd6, 0xe6, 0x26, 0x57,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x24, 0xe8, 0x8e, 0x36, 0xae, 0x01, 0x00, 0x00,
}
